"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class LogMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOG_LEVEL_FIELD_NUMBER: builtins.int
    LOGGER_FIELD_NUMBER: builtins.int
    MAC_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    log_level: builtins.str
    """may contain the values DEBUG, INFO, WARNING or ERROR"""
    logger: builtins.str
    """Identifier where in the client application this message originated from"""
    mac: builtins.bytes
    """MAC address of the system running the client application"""
    message: builtins.str
    """free-form log message"""
    def __init__(
        self,
        *,
        log_level: builtins.str | None = ...,
        logger: builtins.str | None = ...,
        mac: builtins.bytes | None = ...,
        message: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["log_level", b"log_level", "logger", b"logger", "mac", b"mac", "message", b"message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["log_level", b"log_level", "logger", b"logger", "mac", b"mac", "message", b"message"]) -> None: ...

global___LogMessage = LogMessage
